[package]
name = "cute_lights_factorio_wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
colors-transform = "0.2.11"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.38.0", features = ["full"] }
